<?php

namespace App\Enums;

enum TaskType: string
{
    case NEW_MESSAGE = 'NEW_MESSAGE';
    case MATCH_FOUND = 'MATCH_FOUND';
    case BOOKING_PENDING = 'BOOKING_PENDING';
    case BOOKING_CONFIRMED = 'BOOKING_CONFIRMED';
    case BOOKING_COMPLETED = 'BOOKING_COMPLETED';
    case BOOKING_CANCELED = 'BOOKING_CANCELED';
    case REVIEW_RECEIVED = 'REVIEW_RECEIVED';
    case PAYMENT_RECEIVED = 'PAYMENT_RECEIVED';
    case TRAINING_AVAILABLE = 'TRAINING_AVAILABLE';
}